Vag file
c-luu/c-luu.github.io pull request #5
Opened 2019-09-01 02:29 UTC by nyl1221

2019-09-01 14:10 UTC, c-luu requested changes
Lastly, please run `vagrant up` in this project directory to see if the current blogs serve without issues.

2019-09-01 14:10 UTC, c-luu commented on Vagrantfile
> +	#config.vm.provision "shell", path: "bootstrap.sh", privileged: false
remove comment

2019-09-01 14:10 UTC, c-luu commented on bootstrap.sh
> +if [ ! -f jekyll/_config.yml ]; then
line 28 down to 33 could break the script since I don't have a `/jekyll` directory, nor do I need one. Line 34 onward should be able to run just fine in the `/vagrant` working dir.

2019-09-04 02:03 UTC, nyl1221 commented
To be continued....

[link]`https://gist.github.com/c-luu/a9d7254d86d8b1ed3fc6f842eb123c85` 

1. add installations in vagrant file vs. bash script to execute at root level.
2. then test it in vagfile branch.

2021-03-14 16:31 UTC, closed without merging